print("why did the banana go to the doctor")
input("")
print("because he wasn't peeling well")
input("")
print("Why do bananas use sunblock?")
input("")
print("Because otherwise they would peel.") 
input("")
print("You need to be extra nice to bananas, you know why?")
input("")
print("You don't want to hurt their peelings.")
input("")
print("Why do monkeys like bananas so much?")
input("")
print("Because they are very apeeling")