print("hello im MR.STORYBOT")
print("and today we are going to create a great story")
name = input("what is your name ")
print(f"well its great to meet you {name}")
input("")
print("lets do a small interview")
input("")
name2 = input("what is the name of one of your friends: ")
class1 = input("what is your favorite class: ")
class2 = input("cool, give me your least favorite class: ")
animal1 = input(f"i also dislike {class2} what is your favorite animal in the singular: ")
input("lets start the story press enter too progress")
input("")
print(f"one sunny day {name2} was walking to their first class")
input("")
print(f"as {name2} was walking they realized they weren't sure what class they had")
input("")
print(f"it was the first day of the trimester and {name2} hadn't checked their schedule")
input("")
print(f"taking a guess, {name2} decided to go to {class2}")
input("")
print(f"as they arrived, {name2} saw an {animal1} running around the classroom")
input("")
print(f"{name2} being unsure what to do sat down and decided to let it play out")
input("")
print(f"the {animal1} ran out the door and escaped the building")
input("")
print(f"{name2} decided to stay in the class as everyone acted like nothing happened")
input("")
print(f"as {class2} progressed {name2} realized they had went to the wrong class after 30 minutes of not realizing")
input("")
print(f"defeated, they left the classroom, made their way to the front desk, and got their schedule")
input("")
print(f"discovering they had {class1} they happily pranced their way there")
input("")
print(f"{name2}, a little embarrassed, walked into {class1} and signed in")
input("")
print(f"{name2} took their seat next to {name} and lived happily ever after... ")
input("")
print("the end")