print("hello im MR.STORYBOT")
print("and today we are going to create a great story")
name = input("what is your name ")
print(f"well its great to meet you {name}")
input("")
print("lets do a small interview")
input("")
classone = input("what is your favorite class")
input("")
classtwo = input("cool, give me your least favorite class")
input("")
print(f"one sunny day {name} was walking to their first class")
print("")